# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
      gunzip elm.gz
      chmod +x elm
      sudo mv elm /usr/local/bin/
      elm --help
    displayName: 'Install elm'

  - script: |
      mkdir dist
      cp index.html dist/index.html
      cp favicon.ico dist/favicon.ico
    displayName: 'Copy files in dist folder'

  - script: |
      elm make src/Main.elm --optimize --output=dist/main.js
    displayName: 'Compile main.js'

  - publish: 'dist' # path to a file or folder
    artifact: 'dist' # artifact name
    displayName: 'Publish artifact'
